version: "3.7"
services:
  frontend:
    container_name: frontend
    image: $WERF_FRONTEND_DOCKER_IMAGE_NAME
    networks:
      - nginx_net
  backend:
    container_name: backend
    image: $WERF_BACKEND_DOCKER_IMAGE_NAME
    networks:
      - nginx_net
  nginx:
    container_name: stats-informer-nginx
    image: nginx:stable-alpine
    restart: unless-stopped
    networks:
      - nginx_net
    volumes:
      - ./.configs/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''

networks:
  nginx_net:
    name: nginx_net
